# Generated by Django 2.2 on 2019-06-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_training'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='date',
            field=models.DateField(verbose_name='training date'),
        ),
    ]
